export default {
	top_pic: require('./images/top-pic.png'),
	total_icon: require('./images/total-icon.png'),
	total_integral_icon: require('./images/total-integral-icon.png'),
	eye_display_icon: require('./images/eye-display-icon.png'),
	eye_hide_icon: require('./images/eye-hide-icon.png'),
	back_arrow_icon: require('./images/back-arrow-icon.png'),
	title_more_arrow: require('./images/title-more-arrow.png'),
	sort_select_icon: require('./images/sort-select-icon.png'),
	sortbar_search_icon: require('./images/sortbar-search-icon.png'),
	search_icon: require('./images/search-icon.png'),
	close_popup_icon: require('./images/close-popup-icon.png'),
	tree_icon: require('./images/icon_tree.png'),
  
	//header
	menu_date_icon_max: require('./images/menu-date-icon-max.png'),
	menu_arrow_icon: require('./images/menu-arrow-icon.png'),
	//tabbar
	toolbar_overview_icon_nl: require('./images/toolbar-overview-icon-nl.png'),
	toolbar_overview_icon_hl: require('./images/toolbar-overview-icon-hl.png'),
	toolbar_sales_icon_nl: require('./images/toolbar-sales-icon-nl.png'),
	toolbar_sales_icon_hl: require('./images/toolbar-sales-icon-hl.png'),
	toolbar_member_icon_nl: require('./images/toolbar-member-icon-nl.png'),
	toolbar_member_icon_hl: require('./images/toolbar-member-icon-hl.png'),
	toolbar_marking_icon_nl: require('./images/toolbar-marking-icon-nl.png'),
	toolbar_marking_icon_hl: require('./images/toolbar-marking-icon-hl.png'),
	toolbar_more_icon_nl: require('./images/toolbar-more-icon-nl.png'),
	toolbar_more_icon_hl: require('./images/toolbar-more-icon-hl.png'),
	toolbar_lock: require('./images/lock.png'),
	//more
	menubar_setting_icon: require('./images/menubar-setting-icon.png'),
	more_commodity_icon: require('./images/more-commodity-icon.png'),
	more_staff_icon: require('./images/more-staff-icon.png'),
	more_shop_icon: require('./images/more-shop-icon.png'),
	more_cargo_flow_icon: require('./images/more-cargo-flow-icon.png'),
	more_monitor_icon: require('./images/more-monitor-icon.png'),
	icon_right: require('./images/icon_right.png'),
	more_setting_icon: require('./images/more-setting-icon.png'),
	more_notice_icon: require('./images/more-notice-icon.png'),
	more_log_icon: require('./images/more-log-icon.png'),
	more_feedback_icon: require('./images/more-feedback-icon.png'),
  
	// overview
	menu_date_icon_min: require('./images/menu-date-icon-min.png'),
	scape_windmill_pic: require('./images/scape-windmill-pic.png'),
	scape_glare_pic: require('./images/scape-glare-pic.png'),
	title_more_main_arrow: require('./images/title-more-main-arrow.png'),
	anti_checkout_icon: require('./images/anti-checkout-icon.png'),
	back_food_icon: require('./images/back-food-icon.png'),
	abor_free_icon: require('./images/abor-free-icon.png'),
	abor_gifts_icon: require('./images/abor-gifts-icon.png'),
	abor_withdrawal_icon: require('./images/abor-withdrawal-icon.png'),
	abor_backfood_icon: require('./images/abor-backfood-icon.png'),
	help_icon: require('./images/help-icon.png'),
	business_background: require('./images/business-background.png'),
	customer_background: require('./images/customer-background.png'),
	business: require('./images/business.png'),
	customer: require('./images/customer.png'),
	royalty_background: require('./images/royalty-background.png'),
	member_background: require('./images/member-background.png'),
	sortbar_arrow_hl: require('./images/sortbar-arrow-hl.png'),
	appointment: require('./images/appointment.png'),
	coupons: require('./images/coupons.png'),
	guest: require('./images/guest.png'),
	member: require('./images/member.png'),
	price_overview: require('./images/price_overview.png'),
	refund_overview: require('./images/refund_overview.png'),
	register_overview: require('./images/register_overview.png'),
	send_stamps: require('./images/send_stamps.png'),
  
	//member
	birthday_cake: require('./images/birthday-cake.png'),
	member_golden_icon: require('./images/member-golden-icon.png'),
	member_diamond_icon: require('./images/member-diamond-icon.png'),
	member_silver_icon: require('./images/member-silver-icon.png'),
	member_golddiamond_icon: require('./images/member-golddiamond-icon.png'),
	member_king_icon: require('./images/member-king-icon.png'),
	member_vip_icon: require('./images/member-vip-icon.png'),
	member_none_icon: require('./images/member-none-icon.png'),
	member_top_pic: require('./images/member-top-pic.png'),
  
	//saleOrder
	list_return_icon: require('./images/list-return-icon.png'),
	list_sale_icon: require('./images/list-sale-icon.png'),
	list_anti_checkout_icon: require('./images/list-anti-checkout-icon.png'),
	list_other_icon: require('./images/list-other-icon.png'),
	total_pic: require('./images/total-pic.png'),
	paid_in_pic: require('./images/paid-in-pic.png'),
  
	// marking
	coupon_icon: require('./images/coupon-icon.png'),
	expire_coupon_icon: require('./images/expire-coupon-icon.png'),
	write_off_coupon_icon: require('./images/write-off-coupon-icon.png'),
	write_coupon_icon: require('./images/write-coupon-icon.png'),
	promotional_card: require('./images/promotional-card.png'),
	coupon_card: require('./images/coupon-card.png'),
	shopping_card: require('./images/shopping-card.png'),
	secondary_card: require('./images/secondary-card.png'),
	promotional_card_lose: require('./images/promotional-card-lose.png'),
	coupon_card_lose: require('./images/coupon-card-lose.png'),
	shopping_card_lose: require('./images/shopping-card-lose.png'),
	secondary_card_lose: require('./images/secondary-card-lose.png'),
  
	// more
	temp_logo_pic: require('./images/temp-logo-pic.png'),
	arrow_down_red_icon: require('./images/arrow-down-red-icon.png'),
	arrow_level_blue_icon: require('./images/arrow-level-blue-icon.png'),
	arrow_up_green_icon: require('./images/arrow-up-green-icon.png'),
	ziying_logo_icon: require('./images/ziying-logo-icon.png'),
	meituan_logo_icon: require('./images/meituan-logo-icon.png'),
	eleme_logo_icon: require('./images/eleme-logo-icon.png'),
	baiduwaim_logo_icon: require('./images/baiduwaim-logo-icon.png'),
	tuan_logo_icon: require('./images/tuan-logo-icon.png'),
	other_logo_icon: require('./images/other-logo-icon.png'),
	multi_select_hl: require('./images/multi-select-hl.png'),
	multi_select_nl: require('./images/multi-select-nl.png'),
	dot_del_icon: require('./images/dot-del-icon.png'),
	add_pic_box: require('./images/add-pic-box.png'),
	name_edit: require('./images/name-edit.png'),
	camera_play: require('./images/camera-play.png'),
	bg_inventory: require('./images/bg_inventory.png'),
	icon_positive: require('./images/icon_positive.png'),
	icon_positive_normal: require('./images/icon_positive-normal.png'),
  
	// ad
	icon_right_blue: require('./images/icon_right_blue.png'),
	icon_promote: require('./images/icon_promote.png'),
	icon_pop_close: require('./images/icon_pop_close.png'),
  
  }
  